// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyGlobalSeasonFactor(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyGlobalSeasonFactor'](arg1, arg2, arg3);
}

export function BackupDatabase(arg1) {
  return window['go']['main']['App']['BackupDatabase'](arg1);
}

export function ClearMockData() {
  return window['go']['main']['App']['ClearMockData']();
}

export function CreateAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3, arg4);
}

export function DismissAlert(arg1) {
  return window['go']['main']['App']['DismissAlert'](arg1);
}

export function ExportDataCSV(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExportDataCSV'](arg1, arg2, arg3, arg4, arg5);
}

export function GenerateMockData() {
  return window['go']['main']['App']['GenerateMockData']();
}

export function GeneratePDFReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GeneratePDFReport'](arg1, arg2, arg3);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAdCampaignTrend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAdCampaignTrend'](arg1, arg2, arg3, arg4);
}

export function GetAdCampaigns(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAdCampaigns'](arg1, arg2, arg3, arg4);
}

export function GetAdKeywords(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAdKeywords'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAdOverview(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAdOverview'](arg1, arg2, arg3, arg4);
}

export function GetAdPlacementStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAdPlacementStats'](arg1, arg2, arg3);
}

export function GetAdTargets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAdTargets'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAlerts(arg1, arg2) {
  return window['go']['main']['App']['GetAlerts'](arg1, arg2);
}

export function GetAsinDailyTrend(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAsinDailyTrend'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAsinFeeInfo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAsinFeeInfo'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAsinProfitRank(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAsinProfitRank'](arg1, arg2, arg3, arg4, arg5);
}

export function GetBidSuggestions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetBidSuggestions'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCompetitivePrices(arg1, arg2) {
  return window['go']['main']['App']['GetCompetitivePrices'](arg1, arg2);
}

export function GetCrossAccountKPI(arg1, arg2) {
  return window['go']['main']['App']['GetCrossAccountKPI'](arg1, arg2);
}

export function GetCurrentTimes(arg1) {
  return window['go']['main']['App']['GetCurrentTimes'](arg1);
}

export function GetDailyProfitCalendar(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDailyProfitCalendar'](arg1, arg2, arg3);
}

export function GetDailyTrend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDailyTrend'](arg1, arg2, arg3, arg4);
}

export function GetDashboardKPI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDashboardKPI'](arg1, arg2, arg3, arg4);
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetExchangeRates() {
  return window['go']['main']['App']['GetExchangeRates']();
}

export function GetFinanceSummary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFinanceSummary'](arg1, arg2, arg3, arg4);
}

export function GetFinanceVATBreakdown(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFinanceVATBreakdown'](arg1, arg2, arg3, arg4);
}

export function GetInventoryAge(arg1, arg2) {
  return window['go']['main']['App']['GetInventoryAge'](arg1, arg2);
}

export function GetInventoryItems(arg1, arg2) {
  return window['go']['main']['App']['GetInventoryItems'](arg1, arg2);
}

export function GetInventoryOverview(arg1, arg2) {
  return window['go']['main']['App']['GetInventoryOverview'](arg1, arg2);
}

export function GetMarketplaceTimezone(arg1) {
  return window['go']['main']['App']['GetMarketplaceTimezone'](arg1);
}

export function GetMarketplaces() {
  return window['go']['main']['App']['GetMarketplaces']();
}

export function GetPlacementSummary(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPlacementSummary'](arg1, arg2, arg3);
}

export function GetPriceAlertConfig(arg1) {
  return window['go']['main']['App']['GetPriceAlertConfig'](arg1);
}

export function GetPriceHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPriceHistory'](arg1, arg2, arg3, arg4);
}

export function GetProductCosts(arg1) {
  return window['go']['main']['App']['GetProductCosts'](arg1);
}

export function GetProfitMarginTrend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetProfitMarginTrend'](arg1, arg2, arg3, arg4);
}

export function GetReplenishmentAdvice(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReplenishmentAdvice'](arg1, arg2, arg3);
}

export function GetReturnDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReturnDetails'](arg1, arg2, arg3);
}

export function GetReturnRateByASIN(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReturnRateByASIN'](arg1, arg2, arg3);
}

export function GetReturnReasonDistribution(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetReturnReasonDistribution'](arg1, arg2, arg3);
}

export function GetSalesByAsin(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetSalesByAsin'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSearchTermStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSearchTermStats'](arg1, arg2, arg3);
}

export function GetSeasonConfig(arg1) {
  return window['go']['main']['App']['GetSeasonConfig'](arg1);
}

export function GetSettlements(arg1) {
  return window['go']['main']['App']['GetSettlements'](arg1);
}

export function GetSyncHistory(arg1) {
  return window['go']['main']['App']['GetSyncHistory'](arg1);
}

export function GetUnreadAlertCount(arg1) {
  return window['go']['main']['App']['GetUnreadAlertCount'](arg1);
}

export function GetVATRates(arg1) {
  return window['go']['main']['App']['GetVATRates'](arg1);
}

export function ImportCostCSV(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportCostCSV'](arg1, arg2, arg3);
}

export function MarkAlertRead(arg1) {
  return window['go']['main']['App']['MarkAlertRead'](arg1);
}

export function OpenFileInExplorer(arg1) {
  return window['go']['main']['App']['OpenFileInExplorer'](arg1);
}

export function ResetVATRate(arg1, arg2) {
  return window['go']['main']['App']['ResetVATRate'](arg1, arg2);
}

export function SaveCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCredential'](arg1, arg2, arg3);
}

export function SaveCustomVATRate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveCustomVATRate'](arg1, arg2, arg3);
}

export function SavePriceAlertConfig(arg1) {
  return window['go']['main']['App']['SavePriceAlertConfig'](arg1);
}

export function SaveProductCost(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveProductCost'](arg1, arg2, arg3, arg4);
}

export function SaveSeasonConfig(arg1) {
  return window['go']['main']['App']['SaveSeasonConfig'](arg1);
}

export function SyncCatalogMetadata(arg1, arg2) {
  return window['go']['main']['App']['SyncCatalogMetadata'](arg1, arg2);
}

export function SyncExchangeRates() {
  return window['go']['main']['App']['SyncExchangeRates']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TriggerSync(arg1, arg2, arg3) {
  return window['go']['main']['App']['TriggerSync'](arg1, arg2, arg3);
}

export function UpdateReplenishmentConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateReplenishmentConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSkuSeasonFactor(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSkuSeasonFactor'](arg1, arg2, arg3);
}
