// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {services} from '../models';

export function ApplyGlobalSeasonFactor(arg1:number,arg2:string,arg3:number):Promise<void>;

export function BackupDatabase(arg1:string):Promise<Record<string, any>>;

export function ClearMockData():Promise<Record<string, any>>;

export function CreateAccount(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<number>;

export function DismissAlert(arg1:number):Promise<void>;

export function ExportDataCSV(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function GenerateMockData():Promise<Record<string, any>>;

export function GeneratePDFReport(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function GetAccounts():Promise<Array<main.AccountInfo>>;

export function GetAdCampaignTrend(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Array<Record<string, any>>>;

export function GetAdCampaigns(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Array<main.AdCampaignSummary>>;

export function GetAdKeywords(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<services.AdKeywordRow>>;

export function GetAdOverview(arg1:number,arg2:string,arg3:string,arg4:string):Promise<services.AdOverview>;

export function GetAdPlacementStats(arg1:number,arg2:string,arg3:string):Promise<Array<services.PlacementRow>>;

export function GetAdTargets(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<services.AdTargetRow>>;

export function GetAlerts(arg1:number,arg2:boolean):Promise<Array<services.Alert>>;

export function GetAsinDailyTrend(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<services.AsinDailyPoint>>;

export function GetAsinFeeInfo(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<services.AsinFeeInfo>;

export function GetAsinProfitRank(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Record<string, any>>;

export function GetBidSuggestions(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<services.BidSuggestion>>;

export function GetCompetitivePrices(arg1:number,arg2:string):Promise<Array<services.CompetitivePriceItem>>;

export function GetCrossAccountKPI(arg1:string,arg2:string):Promise<services.CrossAccountKPI>;

export function GetCurrentTimes(arg1:string):Promise<Record<string, string>>;

export function GetDailyProfitCalendar(arg1:number,arg2:string,arg3:string):Promise<Array<services.DailyProfitCell>>;

export function GetDailyTrend(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Array<services.DailyDataPoint>>;

export function GetDashboardKPI(arg1:number,arg2:string,arg3:string,arg4:string):Promise<services.DashboardKPI>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetExchangeRates():Promise<Array<services.CurrencyRate>>;

export function GetFinanceSummary(arg1:number,arg2:string,arg3:string,arg4:string):Promise<services.FinanceSummary>;

export function GetFinanceVATBreakdown(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetInventoryAge(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetInventoryItems(arg1:number,arg2:string):Promise<Array<services.InventoryItem>>;

export function GetInventoryOverview(arg1:number,arg2:string):Promise<services.InventoryOverview>;

export function GetMarketplaceTimezone(arg1:string):Promise<string>;

export function GetMarketplaces():Promise<Array<main.MarketplaceInfo>>;

export function GetPlacementSummary(arg1:number,arg2:string,arg3:string):Promise<Array<Record<string, any>>>;

export function GetPriceAlertConfig(arg1:number):Promise<services.PriceAlertConfig>;

export function GetPriceHistory(arg1:number,arg2:string,arg3:string,arg4:number):Promise<Array<Record<string, any>>>;

export function GetProductCosts(arg1:number):Promise<Array<Record<string, any>>>;

export function GetProfitMarginTrend(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Array<services.ProfitMarginPoint>>;

export function GetReplenishmentAdvice(arg1:number,arg2:string,arg3:number):Promise<Array<services.ReplenishmentAdvice>>;

export function GetReturnDetails(arg1:number,arg2:string,arg3:number):Promise<Array<services.ReturnDetail>>;

export function GetReturnRateByASIN(arg1:number,arg2:string,arg3:number):Promise<Array<services.ReturnRateByASIN>>;

export function GetReturnReasonDistribution(arg1:number,arg2:string,arg3:number):Promise<Array<services.ReturnReasonStat>>;

export function GetSalesByAsin(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<services.SalesByAsin>>;

export function GetSearchTermStats(arg1:number,arg2:string,arg3:string):Promise<Array<services.SearchTermStat>>;

export function GetSeasonConfig(arg1:number):Promise<services.SeasonConfig>;

export function GetSettlements(arg1:number):Promise<Array<services.SettlementSummary>>;

export function GetSyncHistory(arg1:number):Promise<Array<Record<string, any>>>;

export function GetUnreadAlertCount(arg1:number):Promise<number>;

export function GetVATRates(arg1:number):Promise<Array<services.VATRate>>;

export function ImportCostCSV(arg1:number,arg2:string,arg3:string):Promise<services.CostImportResult>;

export function MarkAlertRead(arg1:number):Promise<void>;

export function OpenFileInExplorer(arg1:string):Promise<Record<string, any>>;

export function ResetVATRate(arg1:number,arg2:string):Promise<void>;

export function SaveCredential(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SaveCustomVATRate(arg1:number,arg2:string,arg3:number):Promise<void>;

export function SavePriceAlertConfig(arg1:services.PriceAlertConfig):Promise<void>;

export function SaveProductCost(arg1:number,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SaveSeasonConfig(arg1:services.SeasonConfig):Promise<void>;

export function SyncCatalogMetadata(arg1:number,arg2:string):Promise<number>;

export function SyncExchangeRates():Promise<void>;

export function TestConnection(arg1:number):Promise<Record<string, any>>;

export function TriggerSync(arg1:number,arg2:string,arg3:string):Promise<Record<string, any>>;

export function UpdateReplenishmentConfig(arg1:number,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function UpdateSkuSeasonFactor(arg1:number,arg2:string,arg3:number):Promise<void>;
